name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools git
          pip install buildozer cython

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses || true

      - name: Build with Buildozer
        run: |
          buildozer init || true
          buildozer android debug
